- name: configuration of backend server
  hosts: backend
  become: yes
  tasks: 
  - name: disable the nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable the nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install the nodejs
    ansible.builtin.package:
     name: nodejs
     state: present

  - name: Adding the expense user
    ansible.builtin.user:
     name: expense
  
  - name: create the app directory
    ansible.builtin.file:
     path: /app
     state: directory