- name: configuration of mysql-server 
  hosts: mysql
  become: yes
  tasks:
  - name: install the mysql-server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: Start the mysqld service
    ansible.builtin.service:
     name: mysqld
     state: started
     

