- name: configuration of mysql-server 
  hosts: mysql
  become: yes
  vars:
   mysql_password: "ExpenseApp@1"
  tasks:
  - name: install the mysql-server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: Start the mysqld service
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  - name: install the python packages
    ansible.builtin.pip:
     name: PyMySQL
     executable: pip3.9
     
  - name: connect the mysql server
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ mysql_password }}"
     login_host: "mysql.chenchudaws82s.online"