- name: configure the mysql DB server
  hosts: mysql
  become: yes
  vars:
   root_password: ExpenseApp@1

  tasks:
  - name: installing the python libraries
    ansible.builtin.pip:
     name: PyMySQL
     executable: pip3.9
    loop:
    - PyMySQL
    - cryptography

  - name: Install the mysql-server
    ansible.builtin.package:
     name: mysql-server
     state: installed

  - name: start and enable the mysql-server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes


  - name: need to connect to mysql
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ root_password }}"
     login_host: mysql.chenchudaws82s.online
     register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "MySQL info: {{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ root_password }} "
    when: mysql_info.failed is true
  
     

