- name: configuration of mysql-server 
  hosts: mysql
  become: yes
  vars:
   mysql_password: "ExpenseApp@1"
  tasks:
  - name: install the mysql libraries
    ansible.builtin.pip:
     name: "{{ item }}"
     executable: pip3.9
    loop:
    - PyMySQL
    

  - name: install the mysql-server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: Start the mysqld service
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  - name: connect the mysql server
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ mysql_password }}"
     login_host: "mysql.chenchudaws82s.online"
    register: mysql_info

  - name: print the output
    ansible.builtin.debug:
     msg: "{{ mysql_info }}"